//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibaryEntity
    {
        public int ID { get; set; }
        public int ID_Type { get; set; }
        public int ID_Category { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Code { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> Year { get; set; }
        public byte[] Photo { get; set; }
        public string Language { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Type Type { get; set; }
    }
}
