//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLibrary.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base(new Helper().ConnectionString)
        {
        }

        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<LibaryEntity> LibaryEntity { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
